[workspace]
members = [
    "integration-tests",
    "node",
    "pallets/subtensor",
    "runtime",
]

[profile.release]
panic = "unwind"
opt-level = 3
codegen-units = 16


[profile.test]
opt-level = 2

[profile.ephemeral-build]
inherits = "release"
opt-level = 2
codegen-units = 8
